version: '3.8'

services:
sincronizador-pensiones:
build: .
image: sincronizador-app:latest
container_name: sincronizador_worker
restart: unless-stopped
env_file:
- .env
command: ["sh", "-c", "while true; do echo 'Ejecutando sincronizacion...'; python consolidar.py; echo 'Esperando 60s...'; sleep 60; done"]